gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "Please configure your playthrough.$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Are you sure about that configuration?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"

gText_Pie_Welcome::
	.string "Oh, wait!\p"
	.string "Before you go, a message from this\n"
	.string "hack's creator:\p"
	.string "Welcome to Pokémon Elite Redux!\p"
	.string "This is a difficulty hack with modern\n"
	.string "mechanics, many quality of life\l"
	.string "changes, and massive Pokémon variety!\p"
	.string "You can build your team using almost\n"
	.string "any Pokémon from the first seven\l"
	.string "generations, and even many gen eight\l"
	.string "Pokémon are catchable!\p"
	.string "Every Pokémon now has up to four\n"
	.string "abilities at the same time.\p"
	.string "There are up to 3 fixed ones,\n"
	.string "called innates.\p"
	.string "You can't change the innates, but\n"
	.string "but you can switch abilities.\p"
	.string "Before you get started, you'll need\n"
	.string "to choose a difficulty setting.\p"
	.string "Currently you can choose between\n"
	.string "Easy, Ace or Elite Mode.\p"
	.string "Please select a mode to learn more\n"
	.string "about it.$"

gText_Pie_NormalMode::
	.string "In Easy Mode, Trainers won't have\n"
	.string "EVs, so you won't need to worry\l"
	.string "about your own Pokémon's stats.\p"
	.string "This difficulty is recommended if\n"
	.string "you're new to difficulty hacks, or\l"
	.string "if you don't want to deal with EVs.\p"
	.string "However, there are restrictions:\p"
	.string "You can't access the bag in Trainer\n"
	.string "Battles, and the Shift battle style is\l"
	.string "disabled.\p"
	.string "So, would you like to play on\n"
	.string "{COLOR GREEN}Easy Mode{COLOR DARK_GRAY}?$"

gText_Pie_HardMode::
	.string "In Normal Mode, Trainers will have EV-\n"
	.string "trained Pokémon, so you might\l"
	.string "want to EV train your own team.\p"
	.string "You can do this very easy - no\n"
	.string "grinding required - so don't let that\l"
	.string "put you off!\p"
	.string "This difficulty is recommended for\n"
	.string "experienced players.\p"
	.string "So, would you like to play on\n"
	.string "Normal Mode?$"

gText_Pie_ChallengeMode::
	.string "Ace Mode is the normal difficulty.\n"
	.string "Every single Trainer has custom EVs.\p"
	.string "It also has these restrictions:\p"
	.string "You can't access the bag in Trainer\n"
	.string "Battles, and the Shift battle style is\l"
	.string "disabled.\p"
	.string "That means you'll follow the same rules\n"
	.string "as your opponents, so good strategy\l"
	.string "and a balanced team are more important\l"
	.string "in this mode.\p"
	.string "So, would you like to play on\n"
	.string "{COLOR BLUE}Ace Mode{COLOR DARK_GRAY}?$"

gText_Pie_EliteMode::
	.string "Elite Mode is the hardest difficulty.\n"
	.string "Every single Trainer has custom EVs.\p"
	.string "It also has more restrictions:\p"
	.string "You have to unlock innates at\n"
	.string "certain levels to use them.\p"
	.string "The good thing about it:\n"
	.string "The AI also has it locked.\p"
	.string "You can't access the bag in Trainer\n"
	.string "Battles, and the Shift battle style is\l"
	.string "disabled.\p"
	.string "You will experience a world of pain.\p"
	.string "This difficulty is only recommended if\n"
	.string "it sounds appealing to you!\p"
	.string "So, would you like to play on\n"
	.string "{COLOR RED}Elite Mode{COLOR DARK_GRAY}?$"

gText_Pie_WhichDifficulty::
	.string "Which difficulty would you like to\n"
	.string "play on?$"

gText_Pie_LevelCaps::
    .string "This hack has built-in level caps\n"
    .string "based on which badges you have.\p"
    .string "If a Pokémon reaches the level cap,\n"
    .string "it'll only get 1 exp per KO until\l"
	.string "you earn the next badge.\p"
    .string "There are currently three different\n"
	.string "settings for level caps.\p"
    .string "Please choose a level cap setting to\n"
    .string "learn more about it.$"

gText_Pie_StandardCaps::
	.string "The Easy Caps setting is NOT what\n"
	.string "the game is designed around.\p"
	.string "With this option, level caps are only\n"
	.string "present for the first six badges.\p"
	.string "After that, there is no cap, and you\n"
	.string "can train all the way to level 100.\p"
	.string "So, would you like to play with\n"
	.string "{COLOR GREEN}Easy{COLOR DARK_GRAY} level caps?$"

gText_Pie_MoreCaps::
	.string "The More Caps setting is a good\n"
	.string "introduction to difficulty hacks.\p"
	.string "With this option, there will be a\n"
	.string "level cap tied to each badge, and you\l"
	.string "won't be able to reach level 100\l"
	.string "before becoming Champion.\p"
	.string "Enemy trainers will sometimes have higher\n"
	.string "leveled pokémon compared to yours,\l"
	.string "so expect to get challenged.\p"
	.string "So, would you like to play with\n"
	.string "{COLOR BLUE}More{COLOR DARK_GRAY} level caps?$"

gText_Pie_StrictCaps::
	.string "The Elite Caps setting is the\n"
	.string "intended difficulty for this game.\p"
	.string "With this option, there will be a\n"
	.string "level cap tied to each badge, and\l"
	.string "enemy trainers will show no mercy.\p"
	.string "You may have to invent new strategies\n"
	.string "for each fight, so tread with caution.\p"
	.string "So, would you like to play with\n"
	.string "{COLOR RED}Elite{COLOR DARK_GRAY} level caps?$"

gText_Pie_WhichLevelCapSetting::
	.string "Which level cap setting would you\n"
	.string "like play on?$"

gText_Pie_Randomizer::
    .string "Great! Now, there's one last thing\n"
    .string "to decide.\l"
    .string "Randomizer Description$"

gText_Pie_WhichRandomizerSetting::
	.string "Do you want to enable the\n"
	.string "Innate Randomizer?$"

gText_Pie_Randomizer_Enabled::
    .string "Do you want to start the game\n"
    .string "with the Innate Randomizer enabled?$"

gText_Pie_Randomizer_Disabled::
    .string "Do you want to start the game\n"
    .string "with the Innate Randomizer disabled?$"

gText_Pie_Documents::
	.string "Great! If you want more information,\n"
	.string "please check the documents that came\l"
	.string "with the hack's patch.\p"
	.string "They cover everything from Pokémon and\n"
	.string "item locations to new ability effects.\p"
	.string "Finally, I hope you enjoy the hack!\n"
	.string "- Darky\p"
	.string "$"
